import React, { useEffect, useState } from 'react';
import { ExecutionState } from '../types';
import { Cpu, Terminal, Play, CheckCircle2 } from 'lucide-react';

interface ExecutionsTabProps { executions: ExecutionState[]; onTriggerExecution: (description: string) => void; }

export const ExecutionsTab: React.FC<ExecutionsTabProps> = ({ executions, onTriggerExecution }) => {
  const [task, setTask] = useState('');
  const [selectedId, setSelectedId] = useState<string | null>(executions[0]?.execution_id || null);
  useEffect(() => { if (!selectedId && executions[0]) setSelectedId(executions[0].execution_id); else if (selectedId && !executions.some((e) => e.execution_id === selectedId)) setSelectedId(executions[0]?.execution_id || null); }, [executions, selectedId]);
  const selectedExec = executions.find((e) => e.execution_id === selectedId) || null;
  const handleRun = (e: React.FormEvent) => { e.preventDefault(); if (!task.trim()) return; onTriggerExecution(task.trim()); setTask(''); };
  return <div className="space-y-6">
    <div className="page-header"><div><div className="eyebrow"><Cpu className="w-4 h-4" /> EXECUTION CENTER</div><h1>Agent execution telemetry</h1><p>Every dispatch uses the same orchestrator and persists lifecycle, model-call, tool-call and retry counters.</p></div><form onSubmit={handleRun} className="flex gap-2"><input value={task} onChange={(e) => setTask(e.target.value)} placeholder="Trigger an execution…" className="composer-input" /><button className="primary-button" type="submit" disabled={!task.trim()}><Play className="w-4 h-4" /> Dispatch</button></form></div>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-4"><section className="space-y-2"><div className="muted text-[10px] uppercase tracking-wider font-bold">Execution history · {executions.length}</div>{executions.length ? executions.map((exec) => <button key={exec.execution_id} onClick={() => setSelectedId(exec.execution_id)} className={`w-full text-left p-4 rounded-xl border transition-all ${selectedId === exec.execution_id ? 'bg-blue-50 border-blue-300 dark:bg-blue-950/30' : 'bg-white border-slate-200 dark:bg-slate-900/50 dark:border-slate-700'}`}><div className="flex items-center justify-between gap-2"><span className="font-mono text-xs font-bold text-slate-900 dark:text-slate-100 truncate">{exec.execution_id}</span><span className="status-chip">{exec.status}</span></div><p className="text-xs text-slate-500 mt-2 truncate">{exec.metadata?.task || exec.request_id || 'No task metadata'}</p><div className="muted text-[10px] mt-2">Models {exec.model_calls} · Tools {exec.tool_calls} · Retries {exec.retries}</div></button>) : <div className="empty-state min-h-[220px]"><Cpu className="w-7 h-7" /><p>No executions yet.</p></div>}</section>
    <section className="lg:col-span-2 settings-card min-h-[360px]"><div className="settings-card-title"><Terminal className="w-4 h-4" /><h2>{selectedExec?.execution_id || 'Execution inspector'}</h2></div>{selectedExec ? <div className="space-y-4 mt-5"><div className="grid grid-cols-3 gap-2"><div className="status-chip justify-center">Models {selectedExec.model_calls}</div><div className="status-chip justify-center">Tools {selectedExec.tool_calls}</div><div className="status-chip justify-center">Retries {selectedExec.retries}</div></div><div className="trace-box !opacity-100 !font-sans !text-xs">{selectedExec.logs?.length ? selectedExec.logs.map((log, idx) => <div key={idx}><CheckCircle2 className="w-3.5 h-3.5" />{log}</div>) : <div className="muted">No execution log lines were persisted for this run.</div>}</div><div className="muted text-xs">Created {new Date(selectedExec.created_at).toLocaleString()}{selectedExec.completed_at ? ` · completed ${new Date(selectedExec.completed_at).toLocaleString()}` : ''}</div></div> : <div className="empty-state min-h-[280px]"><Terminal className="w-7 h-7" /><p>Select an execution from the history.</p></div>}</section></div>
  </div>;
};
