import React, { useEffect, useMemo, useState } from 'react';
import { Activity, BrainCircuit, CheckCircle2, Cpu, Database, Download, Gauge, Moon, Network, Save, Settings, ShieldCheck, SlidersHorizontal, Sun, Terminal, Wifi, Zap } from 'lucide-react';
import { exportDiagnostics, isDiagnosticsEnabled, setDiagnosticsEnabled } from '../diagnostics';
import './SettingsCenterTab.css';

interface Props { darkMode: boolean; setDarkMode: (value: boolean) => void; }
type Role = 'llm' | 'embedding' | 'reranker';
type Runtime = { model_id: string | null; context_window_tokens: number; max_output_tokens: number | null; temperature: number; top_p: number; timeout_seconds: number; context_allocation: { use_conversation_history: boolean; use_memory: boolean; use_knowledge: boolean; max_memory_tokens: number | null; max_knowledge_tokens: number | null; max_history_tokens: number | null; min_retrieval_score: number | null; reserve_output_tokens: number } };
type Profile = { role: Role; executable_path: string; model_path: string; mmproj_path: string; draft_model_path: string; options: Record<string, any> };

const emptyProfile = (role: Role): Profile => ({ role, executable_path: '', model_path: '', mmproj_path: '', draft_model_path: '', options: {} });
const fallbackRuntime = (config: any): Runtime => ({ model_id: config?.llm?.modelId ?? null, context_window_tokens: config?.llm?.runtime?.context_window_tokens ?? config?.llm?.contextWindowTokens ?? 8192, max_output_tokens: config?.llm?.runtime?.max_output_tokens ?? null, temperature: config?.llm?.runtime?.temperature ?? config?.llm?.temperature ?? 0.7, top_p: config?.llm?.runtime?.top_p ?? config?.llm?.topP ?? 1, timeout_seconds: config?.llm?.runtime?.timeout_seconds ?? 60, context_allocation: config?.llm?.runtime?.context_allocation ?? { use_conversation_history: true, use_memory: true, use_knowledge: true, max_memory_tokens: null, max_knowledge_tokens: null, max_history_tokens: null, min_retrieval_score: null, reserve_output_tokens: 0 } });

export const SettingsCenterTab: React.FC<Props> = ({ darkMode, setDarkMode }) => {
  const [config, setConfig] = useState<any>(null); const [health, setHealth] = useState<any>(null); const [error, setError] = useState(''); const [runtime, setRuntime] = useState<Runtime | null>(null); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [diagnosticsEnabled, setDiagEnabled] = useState(isDiagnosticsEnabled()); const [diagnosticSession, setDiagnosticSession] = useState('');
  const [role, setRole] = useState<Role>('llm'); const [profile, setProfile] = useState<Profile>(emptyProfile('llm')); const [profileJson, setProfileJson] = useState('{}'); const [profileSaved, setProfileSaved] = useState(false); const [command, setCommand] = useState(''); const [profileBusy, setProfileBusy] = useState(false);

  const loadAll = async () => {
    setError('');
    try {
      const [c, h, d, p] = await Promise.all([fetch('/api/v1/config').then((r) => r.json()), fetch('/api/v1/health').then((r) => r.json()), fetch('/api/v1/diagnostics/status').then((r) => r.json()), fetch(`/api/v1/config/llama/profiles/${role}`).then((r) => r.json())]);
      setConfig(c); setHealth(h); setRuntime(fallbackRuntime(c)); setDiagnosticSession(d.session_id || '');
      const next = p.profile || emptyProfile(role); setProfile(next); setProfileJson(JSON.stringify(next.options || {}, null, 2));
    } catch (e) { setError(e instanceof Error ? e.message : 'Failed to load settings'); }
  };
  useEffect(() => { void loadAll(); }, [role]);

  const modelMaximum = config?.context?.modelMaximumTokens ?? config?.llm?.capabilities?.context_window_tokens ?? null;
  const contextLabel = useMemo(() => modelMaximum ? `Detected model maximum: ${Number(modelMaximum).toLocaleString()} tokens` : 'Model maximum not reported; manual value is allowed', [modelMaximum]);
  const updateAllocation = (key: string, value: any) => setRuntime((r) => r ? ({ ...r, context_allocation: { ...r.context_allocation, [key]: value } }) : r);

  const saveRuntime = async () => { if (!runtime) return; setSaving(true); setSaved(false); setError(''); try { const response = await fetch('/api/v1/config/runtime', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(runtime) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || 'Runtime configuration was rejected'); setRuntime(data.runtime); setSaved(true); setTimeout(() => setSaved(false), 2500); } catch (e) { setError(e instanceof Error ? e.message : 'Failed to save runtime'); } finally { setSaving(false); } };
  const saveProfile = async () => { setProfileBusy(true); setError(''); try { let options: Record<string, any>; try { options = JSON.parse(profileJson); } catch { throw new Error('Advanced llama.cpp options must be valid JSON.'); } const payload = { ...profile, role, options }; const response = await fetch(`/api/v1/config/llama/profiles/${role}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || 'Failed to save llama.cpp profile'); setProfile(data.profile); setProfileJson(JSON.stringify(data.profile.options || {}, null, 2)); setProfileSaved(true); setTimeout(() => setProfileSaved(false), 2500); } catch (e) { setError(e instanceof Error ? e.message : 'Failed to save llama.cpp profile'); } finally { setProfileBusy(false); } };
  const renderCommand = async () => { setProfileBusy(true); setError(''); try { const options = JSON.parse(profileJson); const response = await fetch('/api/v1/config/llama/command', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...profile, role, options }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || 'Unable to render command'); setCommand(data.shell_command || ''); } catch (e) { setError(e instanceof Error ? e.message : 'Invalid llama.cpp configuration'); } finally { setProfileBusy(false); } };
  const toggleDiagnostics = (value: boolean) => { setDiagEnabled(value); setDiagnosticsEnabled(value); window.location.reload(); };

  return <div className="space-y-6">
    <div className="page-header"><div><div className="eyebrow"><Settings className="w-4 h-4" /> SETTINGS</div><h1>Runtime & Model Control Center</h1><p>All model, context, retrieval and llama.cpp controls are exposed here instead of requiring command-line configuration.</p></div></div>
    {error && <div className="error-banner">{error}</div>}

    <section className="settings-card"><div className="settings-card-title"><Terminal className="w-4 h-4" /><h2>llama.cpp engine profiles</h2></div><p className="muted text-sm">Separate executable/model profiles for LLM, embedding and reranker. Profiles are saved locally and the advanced JSON accepts current and future llama.cpp flags.</p><div className="flex flex-wrap gap-2 mt-4">{(['llm','embedding','reranker'] as Role[]).map((r) => <button key={r} className={`nav-item ${role === r ? 'active' : ''}`} onClick={() => setRole(r)}>{r === 'llm' ? 'LLM' : r === 'embedding' ? 'Embedding' : 'Reranker'}</button>)}</div><div className="settings-form-grid mt-4"><label>llama-server executable<input value={profile.executable_path} onChange={(e) => setProfile({ ...profile, executable_path: e.target.value })} placeholder="C:\\llama.cpp\\llama-server.exe" /></label><label>Model file<input value={profile.model_path} onChange={(e) => setProfile({ ...profile, model_path: e.target.value })} placeholder="C:\\models\\model.gguf" /></label><label>MMProj (optional)<input value={profile.mmproj_path} onChange={(e) => setProfile({ ...profile, mmproj_path: e.target.value })} placeholder="mmproj-BF16.gguf" /></label><label>Draft / MTP model (optional)<input value={profile.draft_model_path} onChange={(e) => setProfile({ ...profile, draft_model_path: e.target.value })} placeholder="mtp-model.gguf" /></label></div><label className="block mt-4">Advanced llama.cpp options — JSON<textarea rows={12} value={profileJson} onChange={(e) => setProfileJson(e.target.value)} spellCheck={false} className="font-mono text-xs" placeholder={'{\n  "threads": 8,\n  "gpu_layers": "all",\n  "context_size": 32768,\n  "flash_attention": "on",\n  "spec_type": "draft-mtp"\n}'} /></label><div className="flex flex-wrap gap-3 mt-4"><button className="primary-button" onClick={saveProfile} disabled={profileBusy}><Save className="w-4 h-4" />{profileBusy ? 'Working…' : 'Save engine profile'}</button><button className="secondary-button" onClick={renderCommand} disabled={profileBusy}>Render command</button>{profileSaved && <span className="settings-inline-note"><CheckCircle2 className="w-4 h-4" />Saved</span>}</div>{command && <div className="settings-inline-note mt-4 block break-all font-mono text-xs">{command}</div>}<p className="muted text-xs mt-3">Saving the profile does not silently restart an external llama-server process. The next engine-manager stage will use these profiles for start/stop/reload.</p></section>

    <section className="settings-card"><div className="settings-card-title"><Gauge className="w-4 h-4" /><h2>Active LLM runtime</h2></div><p className="muted text-sm">Context is a real runtime setting. The application does not impose a 128K ceiling; the detected model capability is used when available.</p>{runtime && <><div className="settings-form-grid"><label>Model ID<input value={runtime.model_id || ''} onChange={(e) => setRuntime({ ...runtime, model_id: e.target.value || null })} placeholder="provider/model" /></label><label>Context window<input type="number" min={256} max={modelMaximum || undefined} step={256} value={runtime.context_window_tokens} onChange={(e) => setRuntime({ ...runtime, context_window_tokens: Number(e.target.value) })} /></label><label>Max output tokens<input type="number" min={1} value={runtime.max_output_tokens ?? ''} onChange={(e) => setRuntime({ ...runtime, max_output_tokens: e.target.value ? Number(e.target.value) : null })} placeholder="Unlimited" /></label><label>Temperature<input type="number" min={0} max={2} step={0.01} value={runtime.temperature} onChange={(e) => setRuntime({ ...runtime, temperature: Number(e.target.value) })} /></label><label>Top P<input type="number" min={0.01} max={1} step={0.01} value={runtime.top_p} onChange={(e) => setRuntime({ ...runtime, top_p: Number(e.target.value) })} /></label><label>Timeout (s)<input type="number" min={1} value={runtime.timeout_seconds} onChange={(e) => setRuntime({ ...runtime, timeout_seconds: Number(e.target.value) })} /></label></div><div className="settings-inline-note mt-4"><Cpu className="w-4 h-4" />{contextLabel}</div></>}</section>

    {runtime && <section className="settings-card"><div className="settings-card-title"><BrainCircuit className="w-4 h-4" /><h2>Context intelligence & memory</h2></div><p className="muted text-sm">Keep the selected context fixed while the agent retrieves only the useful memory and knowledge needed for each message.</p><div className="toggle-grid mt-4">{([['use_conversation_history','Conversation history'],['use_memory','Persistent memory recall every message'],['use_knowledge','Knowledge retrieval']] as const).map(([key,label]) => <label className="toggle-row" key={key}><span>{label}</span><input type="checkbox" checked={Boolean(runtime.context_allocation[key])} onChange={(e) => updateAllocation(key, e.target.checked)} /></label>)}</div><div className="settings-form-grid mt-4"><label>Memory token budget<input type="number" min={0} value={runtime.context_allocation.max_memory_tokens ?? ''} placeholder="Automatic" onChange={(e) => updateAllocation('max_memory_tokens', e.target.value ? Number(e.target.value) : null)} /></label><label>Knowledge token budget<input type="number" min={0} value={runtime.context_allocation.max_knowledge_tokens ?? ''} placeholder="Automatic" onChange={(e) => updateAllocation('max_knowledge_tokens', e.target.value ? Number(e.target.value) : null)} /></label><label>History token budget<input type="number" min={0} value={runtime.context_allocation.max_history_tokens ?? ''} placeholder="Automatic" onChange={(e) => updateAllocation('max_history_tokens', e.target.value ? Number(e.target.value) : null)} /></label><label>Minimum retrieval score<input type="number" min={0} max={1} step={0.01} value={runtime.context_allocation.min_retrieval_score ?? ''} placeholder="No threshold" onChange={(e) => updateAllocation('min_retrieval_score', e.target.value ? Number(e.target.value) : null)} /></label><label>Reserved output tokens<input type="number" min={0} value={runtime.context_allocation.reserve_output_tokens} onChange={(e) => updateAllocation('reserve_output_tokens', Number(e.target.value))} /></label></div><div className="flex gap-3 mt-5"><button className="primary-button" onClick={saveRuntime} disabled={saving}><Save className="w-4 h-4" />{saving ? 'Applying…' : 'Apply runtime profile'}</button>{saved && <span className="settings-inline-note"><CheckCircle2 className="w-4 h-4" />Applied to subsequent executions</span>}</div></section>}

    {config && <section className="settings-card"><div className="settings-card-title"><Network className="w-4 h-4" /><h2>Provider matrix</h2></div><div className="provider-grid">{[['LLM', config.llm, Cpu], ['Embeddings', config.embeddings, Database], ['Reranker', config.reranker, ShieldCheck]].map(([name, item, Icon]) => { const I = Icon as React.ElementType; return <div className="provider-card" key={String(name)}><I className="w-4 h-4" /><div><strong>{String(name)}</strong><span>{item?.provider} · {item?.baseUrl}</span><small>{item?.modelId || 'auto'} · {item?.path || item?.chatCompletionsPath || ''}</small></div><CheckCircle2 className="w-4 h-4 text-emerald-500" /></div>; })}</div><p className="muted text-xs mt-4">Embedding and reranking are separate provider surfaces. Their engine profiles above can be configured independently.</p></section>}

    <section className="settings-card"><div className="settings-card-title"><Zap className="w-4 h-4" /><h2>Execution safety</h2></div><div className="runtime-list"><div><span>Model calls</span><strong>{config?.agent?.maxModelCalls ?? '—'}</strong></div><div><span>Tool calls</span><strong>{config?.agent?.maxToolCalls ?? '—'}</strong></div><div><span>Retries</span><strong>{config?.agent?.maxRetries ?? '—'}</strong></div><div><span>Total model tokens</span><strong>{config?.agent?.maxTotalModelTokens === 0 ? 'Unlimited' : config?.agent?.maxTotalModelTokens ?? '—'}</strong></div></div></section>
    <section className="settings-card"><div className="settings-card-title"><Sun className="w-4 h-4" /><h2>Appearance & diagnostics</h2></div><div className="theme-choice-grid"><button className={`theme-choice ${!darkMode ? 'selected' : ''}`} onClick={() => setDarkMode(false)}><Sun className="w-5 h-5" /><span>Light</span></button><button className={`theme-choice ${darkMode ? 'selected' : ''}`} onClick={() => setDarkMode(true)}><Moon className="w-5 h-5" /><span>Dark</span></button></div><div className="runtime-list mt-5"><div><span>Backend</span><strong><i className={`status-dot ${health?.status === 'ok' || health?.status === 'healthy' ? 'online' : 'offline'}`} />{health?.status || 'unknown'}</strong></div><div><span>Diagnostic session</span><strong className="font-mono text-xs">{diagnosticSession || 'loading'}</strong></div></div><div className="flex flex-wrap gap-3 mt-4"><button className="secondary-button" onClick={() => toggleDiagnostics(!diagnosticsEnabled)}>{diagnosticsEnabled ? 'Disable diagnostics' : 'Enable diagnostics'}</button><button className="primary-button" onClick={exportDiagnostics} disabled={!diagnosticsEnabled}><Download className="w-4 h-4" />Export diagnostic session</button></div></section>
  </div>;
};
